<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ChildMealsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('child_meals')->delete();
        
        \DB::table('child_meals')->insert(array (
            0 => 
            array (
                'id' => 6,
                'meal_id' => 9,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-11-28 12:15:37',
                'updated_at' => '2024-11-28 12:15:48',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            1 => 
            array (
                'id' => 26,
                'meal_id' => 16,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-11-28 13:20:09',
                'updated_at' => '2024-12-05 19:11:10',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            2 => 
            array (
                'id' => 27,
                'meal_id' => 16,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-11-28 13:20:10',
                'updated_at' => '2024-12-05 19:10:57',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            3 => 
            array (
                'id' => 29,
                'meal_id' => 16,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-11-28 13:20:10',
                'updated_at' => '2024-12-05 19:10:48',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            4 => 
            array (
                'id' => 30,
                'meal_id' => 16,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-11-28 13:20:10',
                'updated_at' => '2024-12-05 19:11:01',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            5 => 
            array (
                'id' => 46,
                'meal_id' => 15,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 18:55:10',
                'updated_at' => '2024-12-05 18:59:25',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            6 => 
            array (
                'id' => 47,
                'meal_id' => 15,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 18:55:10',
                'updated_at' => '2024-12-05 19:05:34',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            7 => 
            array (
                'id' => 48,
                'meal_id' => 15,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 18:55:10',
                'updated_at' => '2024-12-05 19:03:11',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            8 => 
            array (
                'id' => 49,
                'meal_id' => 15,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 18:55:10',
                'updated_at' => '2024-12-05 19:10:18',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            9 => 
            array (
                'id' => 50,
                'meal_id' => 15,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 18:55:10',
                'updated_at' => '2024-12-05 19:10:08',
                'price' => 0.15,
                'people_count' => '1',
                'weight' => NULL,
            ),
            10 => 
            array (
                'id' => 53,
                'meal_id' => 17,
                'quantity' => 1,
                'name' => 'غسيل جاف سريع WASH-DRY',
                'created_at' => '2024-12-05 19:11:28',
                'updated_at' => '2024-12-05 19:16:51',
                'price' => 3.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            11 => 
            array (
                'id' => 54,
                'meal_id' => 17,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:11:28',
                'updated_at' => '2024-12-05 19:11:40',
                'price' => 1.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            12 => 
            array (
                'id' => 66,
                'meal_id' => 19,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:29:44',
                'updated_at' => '2024-12-05 19:32:07',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            13 => 
            array (
                'id' => 67,
                'meal_id' => 19,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:29:44',
                'updated_at' => '2024-12-05 19:31:57',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            14 => 
            array (
                'id' => 68,
                'meal_id' => 19,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:29:44',
                'updated_at' => '2024-12-05 19:31:31',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            15 => 
            array (
                'id' => 69,
                'meal_id' => 19,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:29:44',
                'updated_at' => '2024-12-05 19:31:51',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            16 => 
            array (
                'id' => 70,
                'meal_id' => 19,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:29:44',
                'updated_at' => '2024-12-05 19:32:02',
                'price' => 0.15,
                'people_count' => '1',
                'weight' => NULL,
            ),
            17 => 
            array (
                'id' => 71,
                'meal_id' => 19,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:29:44',
                'updated_at' => '2024-12-05 19:31:45',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            18 => 
            array (
                'id' => 72,
                'meal_id' => 20,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:32:24',
                'updated_at' => '2024-12-05 19:33:26',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            19 => 
            array (
                'id' => 73,
                'meal_id' => 20,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:32:24',
                'updated_at' => '2024-12-05 19:33:06',
                'price' => 0.6,
                'people_count' => '1',
                'weight' => NULL,
            ),
            20 => 
            array (
                'id' => 74,
                'meal_id' => 20,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:32:24',
                'updated_at' => '2024-12-05 19:32:54',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            21 => 
            array (
                'id' => 75,
                'meal_id' => 20,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:32:24',
                'updated_at' => '2024-12-05 19:33:00',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            22 => 
            array (
                'id' => 76,
                'meal_id' => 20,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:32:24',
                'updated_at' => '2024-12-05 19:33:19',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            23 => 
            array (
                'id' => 77,
                'meal_id' => 20,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:32:24',
                'updated_at' => '2024-12-05 19:32:47',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            24 => 
            array (
                'id' => 78,
                'meal_id' => 21,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:41:46',
                'updated_at' => '2024-12-05 19:42:34',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            25 => 
            array (
                'id' => 79,
                'meal_id' => 21,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:41:46',
                'updated_at' => '2024-12-05 19:42:23',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            26 => 
            array (
                'id' => 80,
                'meal_id' => 21,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:41:46',
                'updated_at' => '2024-12-05 19:42:00',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            27 => 
            array (
                'id' => 81,
                'meal_id' => 21,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:41:47',
                'updated_at' => '2024-12-05 19:42:18',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            28 => 
            array (
                'id' => 82,
                'meal_id' => 21,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:41:47',
                'updated_at' => '2024-12-05 19:42:36',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            29 => 
            array (
                'id' => 83,
                'meal_id' => 21,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:41:47',
                'updated_at' => '2024-12-05 19:42:12',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            30 => 
            array (
                'id' => 85,
                'meal_id' => 18,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:42:56',
                'updated_at' => '2024-12-05 19:43:21',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            31 => 
            array (
                'id' => 86,
                'meal_id' => 18,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:42:56',
                'updated_at' => '2024-12-05 19:43:03',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            32 => 
            array (
                'id' => 87,
                'meal_id' => 18,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:42:56',
                'updated_at' => '2024-12-05 19:43:14',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            33 => 
            array (
                'id' => 89,
                'meal_id' => 18,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:42:56',
                'updated_at' => '2024-12-05 19:43:10',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            34 => 
            array (
                'id' => 90,
                'meal_id' => 22,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:43:36',
                'updated_at' => '2024-12-05 19:47:14',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            35 => 
            array (
                'id' => 92,
                'meal_id' => 22,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:43:36',
                'updated_at' => '2024-12-05 19:44:07',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            36 => 
            array (
                'id' => 94,
                'meal_id' => 22,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:43:36',
                'updated_at' => '2024-12-05 19:47:08',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            37 => 
            array (
                'id' => 95,
                'meal_id' => 22,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:43:36',
                'updated_at' => '2024-12-05 19:44:12',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            38 => 
            array (
                'id' => 96,
                'meal_id' => 23,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:47:30',
                'updated_at' => '2024-12-05 19:48:03',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            39 => 
            array (
                'id' => 97,
                'meal_id' => 23,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:47:30',
                'updated_at' => '2024-12-05 19:47:43',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            40 => 
            array (
                'id' => 99,
                'meal_id' => 23,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:47:30',
                'updated_at' => '2024-12-05 19:47:37',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            41 => 
            array (
                'id' => 100,
                'meal_id' => 23,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:47:30',
                'updated_at' => '2024-12-05 19:47:51',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            42 => 
            array (
                'id' => 110,
                'meal_id' => 24,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:49:49',
                'updated_at' => '2024-12-05 19:50:31',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            43 => 
            array (
                'id' => 113,
                'meal_id' => 24,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:49:49',
                'updated_at' => '2024-12-05 19:50:13',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            44 => 
            array (
                'id' => 114,
                'meal_id' => 25,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:52:43',
                'updated_at' => '2024-12-05 19:54:29',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            45 => 
            array (
                'id' => 115,
                'meal_id' => 25,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:52:43',
                'updated_at' => '2024-12-05 19:53:24',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            46 => 
            array (
                'id' => 116,
                'meal_id' => 25,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:52:43',
                'updated_at' => '2024-12-05 19:52:43',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            47 => 
            array (
                'id' => 117,
                'meal_id' => 25,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:52:43',
                'updated_at' => '2024-12-05 19:53:15',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            48 => 
            array (
                'id' => 118,
                'meal_id' => 25,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:52:43',
                'updated_at' => '2024-12-05 19:53:32',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            49 => 
            array (
                'id' => 119,
                'meal_id' => 25,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:52:43',
                'updated_at' => '2024-12-05 19:52:43',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            50 => 
            array (
                'id' => 120,
                'meal_id' => 26,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:55:02',
                'updated_at' => '2024-12-05 19:55:41',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            51 => 
            array (
                'id' => 121,
                'meal_id' => 26,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:55:02',
                'updated_at' => '2024-12-05 19:55:15',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            52 => 
            array (
                'id' => 122,
                'meal_id' => 26,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:55:02',
                'updated_at' => '2024-12-05 19:55:02',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            53 => 
            array (
                'id' => 123,
                'meal_id' => 26,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:55:02',
                'updated_at' => '2024-12-05 19:55:11',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            54 => 
            array (
                'id' => 124,
                'meal_id' => 26,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:55:02',
                'updated_at' => '2024-12-05 19:55:31',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            55 => 
            array (
                'id' => 125,
                'meal_id' => 26,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:55:02',
                'updated_at' => '2024-12-05 19:55:02',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            56 => 
            array (
                'id' => 126,
                'meal_id' => 27,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:55:53',
                'updated_at' => '2024-12-05 19:58:26',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            57 => 
            array (
                'id' => 127,
                'meal_id' => 27,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:55:53',
                'updated_at' => '2024-12-05 19:58:14',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            58 => 
            array (
                'id' => 128,
                'meal_id' => 27,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:55:53',
                'updated_at' => '2024-12-05 19:55:53',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            59 => 
            array (
                'id' => 129,
                'meal_id' => 27,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:55:53',
                'updated_at' => '2024-12-05 19:58:08',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            60 => 
            array (
                'id' => 130,
                'meal_id' => 27,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:55:53',
                'updated_at' => '2024-12-05 19:58:20',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            61 => 
            array (
                'id' => 132,
                'meal_id' => 28,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 19:58:51',
                'updated_at' => '2024-12-05 19:58:51',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            62 => 
            array (
                'id' => 133,
                'meal_id' => 28,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 19:58:51',
                'updated_at' => '2024-12-05 19:58:51',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            63 => 
            array (
                'id' => 134,
                'meal_id' => 28,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 19:58:51',
                'updated_at' => '2024-12-05 19:59:01',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            64 => 
            array (
                'id' => 135,
                'meal_id' => 28,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 19:58:51',
                'updated_at' => '2024-12-05 19:58:51',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            65 => 
            array (
                'id' => 136,
                'meal_id' => 28,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 19:58:51',
                'updated_at' => '2024-12-05 19:58:51',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            66 => 
            array (
                'id' => 137,
                'meal_id' => 28,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 19:58:51',
                'updated_at' => '2024-12-05 19:59:09',
                'price' => 0.7,
                'people_count' => '1',
                'weight' => NULL,
            ),
            67 => 
            array (
                'id' => 140,
                'meal_id' => 29,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:11:20',
                'updated_at' => '2024-12-05 20:11:51',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            68 => 
            array (
                'id' => 143,
                'meal_id' => 29,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:11:20',
                'updated_at' => '2024-12-05 20:11:56',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            69 => 
            array (
                'id' => 146,
                'meal_id' => 30,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:13:03',
                'updated_at' => '2024-12-05 20:13:10',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            70 => 
            array (
                'id' => 152,
                'meal_id' => 31,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:13:38',
                'updated_at' => '2024-12-05 20:14:12',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            71 => 
            array (
                'id' => 158,
                'meal_id' => 32,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:14:23',
                'updated_at' => '2024-12-05 20:14:43',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            72 => 
            array (
                'id' => 162,
                'meal_id' => 33,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:14:54',
                'updated_at' => '2024-12-05 20:15:40',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            73 => 
            array (
                'id' => 163,
                'meal_id' => 33,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:14:54',
                'updated_at' => '2024-12-05 20:15:28',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            74 => 
            array (
                'id' => 165,
                'meal_id' => 33,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:14:54',
                'updated_at' => '2024-12-05 20:15:06',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            75 => 
            array (
                'id' => 166,
                'meal_id' => 33,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:14:54',
                'updated_at' => '2024-12-05 20:15:34',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            76 => 
            array (
                'id' => 170,
                'meal_id' => 34,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:16:26',
                'updated_at' => '2024-12-05 20:16:48',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            77 => 
            array (
                'id' => 173,
                'meal_id' => 34,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:16:26',
                'updated_at' => '2024-12-05 20:16:55',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            78 => 
            array (
                'id' => 174,
                'meal_id' => 12,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:17:25',
                'updated_at' => '2024-12-05 20:17:44',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            79 => 
            array (
                'id' => 176,
                'meal_id' => 12,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:17:25',
                'updated_at' => '2024-12-05 20:18:11',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            80 => 
            array (
                'id' => 178,
                'meal_id' => 12,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:17:25',
                'updated_at' => '2024-12-05 20:17:36',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            81 => 
            array (
                'id' => 179,
                'meal_id' => 12,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:17:25',
                'updated_at' => '2024-12-05 20:18:05',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            82 => 
            array (
                'id' => 182,
                'meal_id' => 37,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:18:38',
                'updated_at' => '2024-12-05 20:19:00',
                'price' => 1.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            83 => 
            array (
                'id' => 188,
                'meal_id' => 38,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:19:12',
                'updated_at' => '2024-12-05 20:19:27',
                'price' => 1.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            84 => 
            array (
                'id' => 193,
                'meal_id' => 14,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:35:08',
                'updated_at' => '2024-12-05 20:35:29',
                'price' => 4.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            85 => 
            array (
                'id' => 194,
                'meal_id' => 14,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:35:08',
                'updated_at' => '2024-12-05 20:35:39',
                'price' => 1.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            86 => 
            array (
                'id' => 195,
                'meal_id' => 14,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:35:08',
                'updated_at' => '2024-12-05 20:35:22',
                'price' => 2.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            87 => 
            array (
                'id' => 197,
                'meal_id' => 14,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:35:08',
                'updated_at' => '2024-12-05 20:35:17',
                'price' => 3.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            88 => 
            array (
                'id' => 199,
                'meal_id' => 13,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:36:24',
                'updated_at' => '2024-12-05 20:36:50',
                'price' => 2.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            89 => 
            array (
                'id' => 200,
                'meal_id' => 13,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:36:24',
                'updated_at' => '2024-12-05 20:36:34',
                'price' => 1.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            90 => 
            array (
                'id' => 201,
                'meal_id' => 13,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:36:24',
                'updated_at' => '2024-12-05 20:36:45',
                'price' => 1.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            91 => 
            array (
                'id' => 203,
                'meal_id' => 13,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:36:24',
                'updated_at' => '2024-12-05 20:36:39',
                'price' => 2.0,
                'people_count' => '1',
                'weight' => NULL,
            ),
            92 => 
            array (
                'id' => 206,
                'meal_id' => 39,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:37:16',
                'updated_at' => '2024-12-05 20:37:33',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            93 => 
            array (
                'id' => 210,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:38:52',
                'updated_at' => '2024-12-05 20:40:02',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            94 => 
            array (
                'id' => 211,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:38:52',
                'updated_at' => '2024-12-05 20:39:57',
                'price' => 0.6,
                'people_count' => '1',
                'weight' => NULL,
            ),
            95 => 
            array (
                'id' => 212,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:38:52',
                'updated_at' => '2024-12-05 20:39:34',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            96 => 
            array (
                'id' => 213,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:38:52',
                'updated_at' => '2024-12-05 20:39:46',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            97 => 
            array (
                'id' => 214,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:38:52',
                'updated_at' => '2024-12-05 20:39:40',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            98 => 
            array (
                'id' => 215,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:38:52',
                'updated_at' => '2024-12-05 20:39:52',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            99 => 
            array (
                'id' => 216,
                'meal_id' => 42,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:40:37',
                'updated_at' => '2024-12-05 20:41:17',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            100 => 
            array (
                'id' => 217,
                'meal_id' => 42,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:40:37',
                'updated_at' => '2024-12-05 20:41:12',
                'price' => 0.6,
                'people_count' => '1',
                'weight' => NULL,
            ),
            101 => 
            array (
                'id' => 218,
                'meal_id' => 42,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:40:37',
                'updated_at' => '2024-12-05 20:40:50',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            102 => 
            array (
                'id' => 219,
                'meal_id' => 42,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:40:37',
                'updated_at' => '2024-12-05 20:41:01',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            103 => 
            array (
                'id' => 220,
                'meal_id' => 42,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:40:37',
                'updated_at' => '2024-12-05 20:40:55',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            104 => 
            array (
                'id' => 221,
                'meal_id' => 42,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:40:37',
                'updated_at' => '2024-12-05 20:41:08',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            105 => 
            array (
                'id' => 222,
                'meal_id' => 11,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:42:03',
                'updated_at' => '2024-12-05 20:43:00',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            106 => 
            array (
                'id' => 223,
                'meal_id' => 11,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:42:03',
                'updated_at' => '2024-12-05 20:42:55',
                'price' => 0.6,
                'people_count' => '1',
                'weight' => NULL,
            ),
            107 => 
            array (
                'id' => 224,
                'meal_id' => 11,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:42:03',
                'updated_at' => '2024-12-05 20:42:32',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            108 => 
            array (
                'id' => 225,
                'meal_id' => 11,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:42:03',
                'updated_at' => '2024-12-05 20:42:46',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            109 => 
            array (
                'id' => 226,
                'meal_id' => 11,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:42:03',
                'updated_at' => '2024-12-05 20:42:41',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            110 => 
            array (
                'id' => 227,
                'meal_id' => 11,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:42:03',
                'updated_at' => '2024-12-05 20:42:52',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            111 => 
            array (
                'id' => 229,
                'meal_id' => 9,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:43:24',
                'updated_at' => '2024-12-05 20:43:53',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            112 => 
            array (
                'id' => 231,
                'meal_id' => 9,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:43:25',
                'updated_at' => '2024-12-05 20:43:58',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            113 => 
            array (
                'id' => 232,
                'meal_id' => 9,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:43:25',
                'updated_at' => '2024-12-05 20:43:39',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            114 => 
            array (
                'id' => 236,
                'meal_id' => 5,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:45:15',
                'updated_at' => '2024-12-05 20:45:33',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            115 => 
            array (
                'id' => 241,
                'meal_id' => 8,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:45:51',
                'updated_at' => '2024-12-05 20:46:05',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            116 => 
            array (
                'id' => 242,
                'meal_id' => 8,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:45:52',
                'updated_at' => '2024-12-05 20:46:10',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            117 => 
            array (
                'id' => 243,
                'meal_id' => 8,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:45:52',
                'updated_at' => '2024-12-05 20:46:00',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            118 => 
            array (
                'id' => 245,
                'meal_id' => 8,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:45:52',
                'updated_at' => '2024-12-05 20:46:17',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            119 => 
            array (
                'id' => 248,
                'meal_id' => 7,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:46:44',
                'updated_at' => '2024-12-05 20:47:01',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            120 => 
            array (
                'id' => 251,
                'meal_id' => 7,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:46:44',
                'updated_at' => '2024-12-05 20:47:05',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            121 => 
            array (
                'id' => 252,
                'meal_id' => 48,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:47:16',
                'updated_at' => '2024-12-05 20:47:36',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            122 => 
            array (
                'id' => 253,
                'meal_id' => 48,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:47:16',
                'updated_at' => '2024-12-05 20:47:31',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            123 => 
            array (
                'id' => 254,
                'meal_id' => 48,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:47:16',
                'updated_at' => '2024-12-05 20:47:22',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            124 => 
            array (
                'id' => 256,
                'meal_id' => 48,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:47:16',
                'updated_at' => '2024-12-05 20:47:27',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            125 => 
            array (
                'id' => 258,
                'meal_id' => 49,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:48:03',
                'updated_at' => '2024-12-05 20:48:32',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            126 => 
            array (
                'id' => 259,
                'meal_id' => 49,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:48:03',
                'updated_at' => '2024-12-05 20:48:23',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            127 => 
            array (
                'id' => 261,
                'meal_id' => 49,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:48:03',
                'updated_at' => '2024-12-05 20:48:16',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            128 => 
            array (
                'id' => 262,
                'meal_id' => 49,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:48:03',
                'updated_at' => '2024-12-05 20:48:10',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            129 => 
            array (
                'id' => 264,
                'meal_id' => 50,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:48:48',
                'updated_at' => '2024-12-05 20:49:11',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            130 => 
            array (
                'id' => 266,
                'meal_id' => 50,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:48:48',
                'updated_at' => '2024-12-05 20:48:56',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            131 => 
            array (
                'id' => 268,
                'meal_id' => 50,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:48:48',
                'updated_at' => '2024-12-05 20:49:00',
                'price' => 0.1,
                'people_count' => '1',
                'weight' => NULL,
            ),
            132 => 
            array (
                'id' => 269,
                'meal_id' => 50,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:48:48',
                'updated_at' => '2024-12-05 20:49:04',
                'price' => 0.4,
                'people_count' => '1',
                'weight' => NULL,
            ),
            133 => 
            array (
                'id' => 270,
                'meal_id' => 2,
                'quantity' => 1,
                'name' => 'IRON-AR كي سريع',
                'created_at' => '2024-12-05 20:49:34',
                'updated_at' => '2024-12-05 20:49:42',
                'price' => 0.2,
                'people_count' => '1',
                'weight' => NULL,
            ),
            134 => 
            array (
                'id' => 271,
                'meal_id' => 2,
                'quantity' => 1,
                'name' => 'WASH DRY-AR غسيل جاف سريع',
                'created_at' => '2024-12-05 20:49:34',
                'updated_at' => '2024-12-05 20:49:48',
                'price' => 0.8,
                'people_count' => '1',
                'weight' => NULL,
            ),
            135 => 
            array (
                'id' => 272,
                'meal_id' => 2,
                'quantity' => 1,
                'name' => 'WASH-NORMAL غسيل و كي',
                'created_at' => '2024-12-05 20:49:34',
                'updated_at' => '2024-12-05 20:50:21',
                'price' => 0.3,
                'people_count' => '1',
                'weight' => NULL,
            ),
            136 => 
            array (
                'id' => 273,
                'meal_id' => 2,
                'quantity' => 1,
                'name' => 'WASH-DRY غسيل جاف',
                'created_at' => '2024-12-05 20:49:34',
                'updated_at' => '2024-12-05 20:49:58',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
            137 => 
            array (
                'id' => 274,
                'meal_id' => 2,
                'quantity' => 1,
                'name' => 'IRON كي',
                'created_at' => '2024-12-05 20:49:34',
                'updated_at' => '2024-12-05 20:50:01',
                'price' => 0.15,
                'people_count' => '1',
                'weight' => NULL,
            ),
            138 => 
            array (
                'id' => 275,
                'meal_id' => 2,
                'quantity' => 1,
                'name' => 'WASH-NORMAL-AR غسيل وكي سريع',
                'created_at' => '2024-12-05 20:49:34',
                'updated_at' => '2024-12-05 20:49:53',
                'price' => 0.5,
                'people_count' => '1',
                'weight' => NULL,
            ),
        ));
        
        
    }
}