<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ChildMealsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('child_meals')->delete();
        
        \DB::table('child_meals')->insert(array (
            0 => 
            array (
                'id' => 1,
                'meal_id' => 4,
                'quantity' => 6,
                'name' => 'سمبوسه',
                'created_at' => '2024-11-10 20:23:04',
                'updated_at' => '2024-11-10 20:23:04',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => '',
            ),
            1 => 
            array (
                'id' => 2,
                'meal_id' => 5,
                'quantity' => 6,
                'name' => 'سمبوسه',
                'created_at' => '2024-11-10 20:23:50',
                'updated_at' => '2024-11-10 20:23:50',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => '',
            ),
            2 => 
            array (
                'id' => 3,
                'meal_id' => 6,
                'quantity' => 9,
                'name' => 'محشي ورق عنب',
                'created_at' => '2024-11-10 20:24:17',
                'updated_at' => '2024-11-10 20:24:17',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => '',
            ),
            3 => 
            array (
                'id' => 4,
                'meal_id' => 7,
                'quantity' => 8,
                'name' => 'محشي ملفوف',
                'created_at' => '2024-11-10 20:24:36',
                'updated_at' => '2024-11-10 20:24:36',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => '',
            ),
            4 => 
            array (
                'id' => 5,
                'meal_id' => 16,
                'quantity' => 16,
                'name' => 'سينابون',
                'created_at' => '2024-11-10 20:26:39',
                'updated_at' => '2024-11-10 20:26:39',
                'price' => 0.0,
                'people_count' => '1',
                'weight' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'meal_id' => 43,
                'quantity' => 2,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:10:58',
                'updated_at' => '2024-11-10 22:10:58',
                'price' => 14.0,
                'people_count' => '8-10',
                'weight' => '',
            ),
            6 => 
            array (
                'id' => 7,
                'meal_id' => 43,
                'quantity' => 4,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:16:05',
                'updated_at' => '2024-11-10 22:16:05',
                'price' => 26.0,
                'people_count' => '14-16',
                'weight' => '',
            ),
            7 => 
            array (
                'id' => 8,
                'meal_id' => 43,
                'quantity' => 6,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:16:25',
                'updated_at' => '2024-11-10 22:16:25',
                'price' => 35.0,
                'people_count' => '20-25',
                'weight' => '',
            ),
            8 => 
            array (
                'id' => 9,
                'meal_id' => 44,
                'quantity' => 2,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:17:11',
                'updated_at' => '2024-11-10 22:17:11',
                'price' => 14.0,
                'people_count' => '8-10',
                'weight' => '',
            ),
            9 => 
            array (
                'id' => 10,
                'meal_id' => 44,
                'quantity' => 4,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:18:07',
                'updated_at' => '2024-11-10 22:18:07',
                'price' => 26.0,
                'people_count' => '16-18',
                'weight' => '',
            ),
            10 => 
            array (
                'id' => 11,
                'meal_id' => 44,
                'quantity' => 6,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:18:59',
                'updated_at' => '2024-11-10 22:18:59',
                'price' => 35.0,
                'people_count' => '20-25',
                'weight' => '',
            ),
            11 => 
            array (
                'id' => 12,
                'meal_id' => 45,
                'quantity' => 1,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:27:16',
                'updated_at' => '2024-11-10 22:27:16',
                'price' => 7.5,
                'people_count' => '5-7',
                'weight' => '',
            ),
            12 => 
            array (
                'id' => 13,
                'meal_id' => 45,
                'quantity' => 2,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:27:33',
                'updated_at' => '2024-11-10 22:27:33',
                'price' => 14.0,
                'people_count' => '10-13',
                'weight' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'meal_id' => 45,
                'quantity' => 4,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:27:51',
                'updated_at' => '2024-11-10 22:27:51',
                'price' => 21.0,
                'people_count' => '16-18',
                'weight' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'meal_id' => 46,
                'quantity' => 1,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:28:29',
                'updated_at' => '2024-11-10 22:37:14',
                'price' => 8.0,
                'people_count' => '5-7',
                'weight' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'meal_id' => 46,
                'quantity' => 2,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:30:22',
                'updated_at' => '2024-11-10 22:42:29',
                'price' => 15.0,
                'people_count' => '10-13',
                'weight' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'meal_id' => 46,
                'quantity' => 4,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:30:43',
                'updated_at' => '2024-11-10 22:30:43',
                'price' => 22.0,
                'people_count' => '16-18',
                'weight' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'meal_id' => 47,
                'quantity' => 1,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:43:40',
                'updated_at' => '2024-11-10 22:43:40',
                'price' => 8.5,
                'people_count' => '5-7',
                'weight' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'meal_id' => 47,
                'quantity' => 2,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:43:55',
                'updated_at' => '2024-11-10 22:43:55',
                'price' => 16.0,
                'people_count' => '10-13',
                'weight' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'meal_id' => 47,
                'quantity' => 4,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:44:11',
                'updated_at' => '2024-11-10 22:44:11',
                'price' => 24.0,
                'people_count' => '16-18',
                'weight' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'meal_id' => 48,
                'quantity' => 1,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:44:57',
                'updated_at' => '2024-11-10 22:45:00',
                'price' => 3.5,
                'people_count' => '0',
                'weight' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'meal_id' => 48,
                'quantity' => 2,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:45:14',
                'updated_at' => '2024-11-10 22:45:20',
                'price' => 6.6,
                'people_count' => '0',
                'weight' => '',
            ),
            22 => 
            array (
                'id' => 23,
                'meal_id' => 48,
                'quantity' => 3,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:45:30',
                'updated_at' => '2024-11-10 22:45:30',
                'price' => 10.0,
                'people_count' => '1',
                'weight' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'meal_id' => 48,
                'quantity' => 4,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:45:38',
                'updated_at' => '2024-11-10 22:45:38',
                'price' => 13.0,
                'people_count' => '1',
                'weight' => '',
            ),
            24 => 
            array (
                'id' => 25,
                'meal_id' => 48,
                'quantity' => 5,
                'name' => 'دجاج',
                'created_at' => '2024-11-10 22:45:44',
                'updated_at' => '2024-11-10 22:45:44',
                'price' => 16.0,
                'people_count' => '1',
                'weight' => '',
            ),
            25 => 
            array (
                'id' => 26,
                'meal_id' => 49,
                'quantity' => 1,
                'name' => 'مرقة الروبيان',
                'created_at' => '2024-11-10 22:59:30',
                'updated_at' => '2024-11-10 22:59:30',
                'price' => 8.5,
                'people_count' => '0',
                'weight' => '1 كيلو',
            ),
            26 => 
            array (
                'id' => 27,
                'meal_id' => 50,
                'quantity' => 1,
                'name' => 'مرقة الروبيان',
                'created_at' => '2024-11-10 23:00:17',
                'updated_at' => '2024-11-10 23:00:17',
                'price' => 24.0,
                'people_count' => '0',
                'weight' => '3 كيلو',
            ),
            27 => 
            array (
                'id' => 28,
                'meal_id' => 51,
                'quantity' => 1,
                'name' => 'حمسة روبيان',
                'created_at' => '2024-11-10 23:00:53',
                'updated_at' => '2024-11-10 23:00:53',
                'price' => 8.0,
                'people_count' => '0',
                'weight' => '1 كيلو',
            ),
            28 => 
            array (
                'id' => 29,
                'meal_id' => 52,
                'quantity' => 1,
                'name' => 'حمسة روبيان',
                'created_at' => '2024-11-10 23:01:26',
                'updated_at' => '2024-11-10 23:01:26',
                'price' => 23.0,
                'people_count' => '0',
                'weight' => '3 كيلو',
            ),
            29 => 
            array (
                'id' => 30,
                'meal_id' => 55,
                'quantity' => 1,
                'name' => 'برياني روبيان + سلطة فتوش',
                'created_at' => '2024-11-10 23:04:23',
                'updated_at' => '2024-11-10 23:04:23',
                'price' => 12.0,
                'people_count' => '5-7',
                'weight' => '0',
            ),
            30 => 
            array (
                'id' => 31,
                'meal_id' => 55,
                'quantity' => 1,
                'name' => 'برياني روبيان + سلطة فتوش',
                'created_at' => '2024-11-10 23:04:44',
                'updated_at' => '2024-11-10 23:04:44',
                'price' => 23.0,
                'people_count' => '10-13',
                'weight' => '0',
            ),
            31 => 
            array (
                'id' => 32,
                'meal_id' => 55,
                'quantity' => 1,
                'name' => 'برياني روبيان + سلطة فتوش',
                'created_at' => '2024-11-10 23:05:00',
                'updated_at' => '2024-11-10 23:05:00',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => '0',
            ),
            32 => 
            array (
                'id' => 33,
                'meal_id' => 56,
                'quantity' => 1,
                'name' => 'برياني أو مكبوس سمك كوفر+ سلطة فتوش',
                'created_at' => '2024-11-10 23:05:47',
                'updated_at' => '2024-11-10 23:05:47',
                'price' => 11.0,
                'people_count' => '5-7',
                'weight' => '0',
            ),
            33 => 
            array (
                'id' => 34,
                'meal_id' => 56,
                'quantity' => 1,
                'name' => 'برياني أو مكبوس سمك كوفر+ سلطة فتوش',
                'created_at' => '2024-11-10 23:06:02',
                'updated_at' => '2024-11-10 23:06:02',
                'price' => 21.0,
                'people_count' => '10-13',
                'weight' => '0',
            ),
            34 => 
            array (
                'id' => 35,
                'meal_id' => 56,
                'quantity' => 1,
                'name' => 'برياني أو مكبوس سمك كوفر+ سلطة فتوش',
                'created_at' => '2024-11-10 23:06:11',
                'updated_at' => '2024-11-10 23:06:11',
                'price' => 31.0,
                'people_count' => '16-18',
                'weight' => '0',
            ),
            35 => 
            array (
                'id' => 36,
                'meal_id' => 57,
                'quantity' => 1,
                'name' => 'برياني أو مكبوس سمك جيذر+ سلطة فتوش',
                'created_at' => '2024-11-10 23:07:03',
                'updated_at' => '2024-11-10 23:07:36',
                'price' => 13.0,
                'people_count' => '5-7',
                'weight' => '0',
            ),
            36 => 
            array (
                'id' => 37,
                'meal_id' => 57,
                'quantity' => 1,
                'name' => 'برياني أو مكبوس سمك جيذر+ سلطة فتوش',
                'created_at' => '2024-11-10 23:07:15',
                'updated_at' => '2024-11-10 23:07:15',
                'price' => 24.0,
                'people_count' => '10-13',
                'weight' => '0',
            ),
            37 => 
            array (
                'id' => 38,
                'meal_id' => 57,
                'quantity' => 1,
                'name' => 'برياني أو مكبوس سمك جيذر+ سلطة فتوش',
                'created_at' => '2024-11-10 23:07:28',
                'updated_at' => '2024-11-10 23:07:28',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => '0',
            ),
            38 => 
            array (
                'id' => 39,
                'meal_id' => 58,
                'quantity' => 1,
                'name' => 'سمك شواء بطريقتنا الخاصة',
                'created_at' => '2024-11-10 23:08:30',
                'updated_at' => '2024-11-10 23:08:30',
                'price' => 6.5,
                'people_count' => '1',
                'weight' => '1 كيلو',
            ),
            39 => 
            array (
                'id' => 40,
                'meal_id' => 59,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:11:43',
                'updated_at' => '2024-11-11 14:11:43',
                'price' => 13.0,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'meal_id' => 59,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:12:04',
                'updated_at' => '2024-11-11 14:12:04',
                'price' => 24.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'meal_id' => 59,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:12:18',
                'updated_at' => '2024-11-11 14:15:09',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'meal_id' => 60,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:14:10',
                'updated_at' => '2024-11-11 14:14:10',
                'price' => 12.5,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'meal_id' => 60,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:14:37',
                'updated_at' => '2024-11-11 14:14:37',
                'price' => 23.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'meal_id' => 60,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:14:58',
                'updated_at' => '2024-11-11 14:14:58',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'meal_id' => 61,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:15:53',
                'updated_at' => '2024-11-11 14:15:53',
                'price' => 12.0,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'meal_id' => 61,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:16:17',
                'updated_at' => '2024-11-11 14:16:17',
                'price' => 23.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'meal_id' => 61,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:16:33',
                'updated_at' => '2024-11-11 14:16:33',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'meal_id' => 62,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:17:20',
                'updated_at' => '2024-11-11 14:17:20',
                'price' => 12.0,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'meal_id' => 62,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:17:40',
                'updated_at' => '2024-11-11 14:17:40',
                'price' => 23.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'meal_id' => 62,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:17:55',
                'updated_at' => '2024-11-11 14:17:55',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'meal_id' => 63,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:18:31',
                'updated_at' => '2024-11-11 14:18:31',
                'price' => 13.0,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'meal_id' => 63,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:18:44',
                'updated_at' => '2024-11-11 14:18:44',
                'price' => 24.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'meal_id' => 63,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:18:56',
                'updated_at' => '2024-11-11 14:18:56',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'meal_id' => 64,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:19:35',
                'updated_at' => '2024-11-11 14:19:35',
                'price' => 13.0,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'meal_id' => 64,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:20:00',
                'updated_at' => '2024-11-11 14:20:00',
                'price' => 24.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'meal_id' => 64,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:20:12',
                'updated_at' => '2024-11-11 14:20:12',
                'price' => 35.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'meal_id' => 65,
                'quantity' => 1,
                'name' => 'صغير',
                'created_at' => '2024-11-11 14:21:27',
                'updated_at' => '2024-11-11 14:21:27',
                'price' => 16.0,
                'people_count' => '5-7',
                'weight' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'meal_id' => 65,
                'quantity' => 1,
                'name' => 'متوسط',
                'created_at' => '2024-11-11 14:21:40',
                'updated_at' => '2024-11-11 14:21:40',
                'price' => 29.0,
                'people_count' => '10-13',
                'weight' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'meal_id' => 65,
                'quantity' => 1,
                'name' => 'كبير',
                'created_at' => '2024-11-11 14:21:55',
                'updated_at' => '2024-11-11 14:21:55',
                'price' => 40.0,
                'people_count' => '16-18',
                'weight' => NULL,
            ),
        ));
        
        
    }
}