<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MealsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('meals')->delete();
        
        \DB::table('meals')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'جبنة دل باستا الخاصة',
                'price' => 3.2,
                'category_id' => 1,
                'description' => NULL,
                'image' => '',
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'جبنة دل باستا البوسنية',
                'price' => 3.2,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'سمن بلدي',
                'price' => 3.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'سمبوسة دل باستا الخاصة دجاج',
                'price' => 1.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'سمبوسة مكس الاجبان',
                'price' => 1.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'محشي ورق عنب',
                'price' => 1.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'محشي ملفوف',
                'price' => 1.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'تشيز فرايز بالدجاج',
                'price' => 1.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'فرايز لحم بالفرن',
                'price' => 1.7,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'باستا بيضاء بالدجاج',
                'price' => 1.7,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'معكرونة سباغيتي بالدجاج',
                'price' => 1.8,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'معكرونة دجاج بالباشميل',
                'price' => 2.5,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'تشيز مشروم باستا',
                'price' => 2.2,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
            'name' => 'داينمت شرمب ( روبيان )',
                'price' => 1.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'بيتزا الدجاج بالصوص الخاص',
                'price' => 2.6,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'سينابون',
                'price' => 2.5,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '',
                'image_url' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'سلطة الفتوش مع الصوص الخاص',
                'price' => 5.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '8-10',
                'image_url' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'سلطة الروب بالخيار',
                'price' => 3.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '8-10',
                'image_url' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'سلطة جرجير رمان بالموزريل',
                'price' => 5.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '8-10',
                'image_url' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'سلطة مشكلة بالصوص الخاص',
                'price' => 5.5,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '8-10',
                'image_url' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'فتة الباذنجان',
                'price' => 5.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '5',
                'image_url' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'حمسة الخضار و الفطر',
                'price' => 5.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '5',
                'image_url' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'مرقة اللحم مع الخضار',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'حمسة لحم ناشف ⁄ مقلي',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'برياني لحم',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'مكبوس لحم',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'مندي لحم',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'بخاري لحم',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'لحم شواء بطريقتنا الخاصة مع برياني خصوصي',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'مرقة الدجاج بالخضار',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'صينية الدجاج والبطاطا',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'برياني هندي بالدجاج',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'مكبوس دجاج',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'رز بخاري بالدجاج',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'برياني خصوصي بالمكسرات + دجاج شواء',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'دجاج الشواء بطريقتنا الخاصة',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'مرقة الروبيان',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'حمسة روبيان',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'برياني روبيان',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'سمك شواء بطريقتنا الخاصة',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'برياني أو مكبوس سمك',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
            'name' => 'ثريد ( دجاج + اللحم )',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'مرقة الدجاج بالخضار + عيش أبيض + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 5,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'صينية الدجاج والبطاطا بالفرن',
                'price' => 0.0,
                'category_id' => 5,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'برياني هندي بالدجاج + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 5,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'مكبوس دجاج + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 5,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'دجاج شواء ، برياني خصوصي + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 5,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'دجاج الشواء بطريقتنا الخاصة',
                'price' => 0.0,
                'category_id' => 5,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'مرقة الروبيان',
                'price' => 8.5,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '0',
                'image_url' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'مرقة الروبيان 3 كيلو',
                'price' => 24.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '0',
                'image_url' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'حمسة روبيان',
                'price' => 0.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '0',
                'image_url' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'حمسة روبيان 3 كيلو',
                'price' => 0.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '0',
                'image_url' => NULL,
            ),
            52 => 
            array (
                'id' => 55,
                'name' => 'برياني روبيان + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            53 => 
            array (
                'id' => 56,
                'name' => 'برياني أو مكبوس سمك كوفر+ سلطة فتوش',
                'price' => 0.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            54 => 
            array (
                'id' => 57,
                'name' => 'برياني أو مكبوس سمك جيذر+ سلطة فتوش',
                'price' => 0.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            55 => 
            array (
                'id' => 58,
                'name' => 'سمك شواء بطريقتنا الخاصة',
                'price' => 0.0,
                'category_id' => 6,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            56 => 
            array (
                'id' => 59,
                'name' => 'مرقة اللحم مع الخضار + عيش أبيض + سلطة الفتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            57 => 
            array (
                'id' => 60,
                'name' => 'حمسة لحم ناشف/مقلي عيش أبيض + سلطة الفتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            58 => 
            array (
                'id' => 61,
                'name' => 'برياني لحم + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            59 => 
            array (
                'id' => 62,
                'name' => 'مكبوس لحم + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            60 => 
            array (
                'id' => 63,
                'name' => 'مندي لحم + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            61 => 
            array (
                'id' => 64,
                'name' => 'بخاري لحم + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            62 => 
            array (
                'id' => 65,
                'name' => 'لحم شواء+ برياني خصوصي +سلطة فتوش',
                'price' => 0.0,
                'category_id' => 7,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            63 => 
            array (
                'id' => 66,
                'name' => 'خروف صومالي',
                'price' => 0.0,
                'category_id' => 8,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            64 => 
            array (
                'id' => 67,
                'name' => 'ذبيحتين شواء بطريقتنا الخاصة',
                'price' => 0.0,
                'category_id' => 8,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            65 => 
            array (
                'id' => 68,
                'name' => 'غوزي لحم ذبيحة كاملة + سلطة فتوش',
                'price' => 0.0,
                'category_id' => 8,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            66 => 
            array (
                'id' => 69,
                'name' => 'بوكس التوفير',
                'price' => 30.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            67 => 
            array (
                'id' => 71,
                'name' => 'سمبوسة مكس الأجبان',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            68 => 
            array (
                'id' => 72,
                'name' => 'سمبوسة شاورما دجاج',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            69 => 
            array (
                'id' => 73,
                'name' => 'سمبوسة جبن مثلثات',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            70 => 
            array (
                'id' => 74,
                'name' => 'تشــباتي',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            71 => 
            array (
                'id' => 75,
                'name' => 'بيتزادجاج بالصوص الخاص',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            72 => 
            array (
                'id' => 76,
                'name' => 'بيتزا نقانق دجاج',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            73 => 
            array (
                'id' => 77,
                'name' => 'سبرنج رول دجاج',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            74 => 
            array (
                'id' => 78,
                'name' => 'ساندويش كرسبي دجاج',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            75 => 
            array (
                'id' => 79,
                'name' => 'شاورما دجاج',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            76 => 
            array (
                'id' => 80,
                'name' => 'تندوري دجاج',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            77 => 
            array (
                'id' => 81,
            'name' => 'دجاج بالتتبيلة الخاصة (مناسب للشوي او القلي)',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            78 => 
            array (
                'id' => 82,
            'name' => 'دجاج بصوص التندوري (مناسب للشوي او القلي)',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            79 => 
            array (
                'id' => 83,
            'name' => 'دجاج بالتتبيلة الهندية (مناسب للكبسة + البرياني + الشوي)',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            80 => 
            array (
                'id' => 84,
                'name' => 'صلصة دل باستا الحمراء',
                'price' => 0.0,
                'category_id' => 10,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            81 => 
            array (
                'id' => 85,
                'name' => 'ترافل المانجو',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            82 => 
            array (
                'id' => 86,
                'name' => 'حلى السنافر',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            83 => 
            array (
                'id' => 87,
                'name' => 'حلى المانجو بالزعفران والشيا',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            84 => 
            array (
                'id' => 88,
                'name' => 'بودينج الشوكلاته',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            85 => 
            array (
                'id' => 89,
                'name' => 'شيز كيك',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            86 => 
            array (
                'id' => 90,
            'name' => 'بودينج الشوكولاته(كبيرة)',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            87 => 
            array (
                'id' => 91,
            'name' => 'حلى المانجا بالزعفران والشيا(كبيره)',
                'price' => 0.0,
                'category_id' => 11,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            88 => 
            array (
                'id' => 92,
                'name' => 'ُ علب عصائر مشكلة',
                'price' => 0.0,
                'category_id' => 12,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            89 => 
            array (
                'id' => 93,
                'name' => 'موهيتو مع الفواكة والكوبات',
                'price' => 0.0,
                'category_id' => 12,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
        ));
        
        
    }
}