<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MealsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('meals')->delete();
        
        \DB::table('meals')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'Dishdasha - دشداشه',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc8655ab.png',
            ),
            1 => 
            array (
                'id' => 5,
                'name' => 'SOCKS جوارب',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc8677da.png',
            ),
            2 => 
            array (
                'id' => 7,
                'name' => 'U T-SHIRT فانية داخلية',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc868533.png',
            ),
            3 => 
            array (
                'id' => 8,
                'name' => 'CAP كاب',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc86927f.png',
            ),
            4 => 
            array (
                'id' => 9,
                'name' => 'ABAYA عبايه',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc869e45.png',
            ),
            5 => 
            array (
                'id' => 11,
                'name' => 'MEN SHIRT قميص رجالي',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc86aad5.png',
            ),
            6 => 
            array (
                'id' => 12,
                'name' => 'SHORT شورت',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc86b631.png',
            ),
            7 => 
            array (
                'id' => 15,
                'name' => 'LADIES DISHDASHA جلابيه',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc86d7d3.png',
            ),
            8 => 
            array (
                'id' => 16,
                'name' => 'Skirt تنوره',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc86e4ab.png',
            ),
            9 => 
            array (
                'id' => 17,
                'name' => 'Wedding Dress فستان سهره',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc86f68f.png',
            ),
            10 => 
            array (
                'id' => 18,
                'name' => 'kumma كمه',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc8700e1.png',
            ),
            11 => 
            array (
                'id' => 19,
                'name' => 'PAKISTANI UNIFORM ملابس باكستان',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc870b06.png',
            ),
            12 => 
            array (
                'id' => 20,
                'name' => 'MILITRY PANTS بنطلون عسكري',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc8715a6.png',
            ),
            13 => 
            array (
                'id' => 21,
                'name' => 'MILITRY SHIRT قميص عسكري',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc871f46.png',
            ),
            14 => 
            array (
                'id' => 22,
                'name' => 'MILITARY UNIFORM ملابس عسكرية',
                'price' => 0.0,
                'category_id' => 4,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc872954.png',
            ),
            15 => 
            array (
                'id' => 23,
                'name' => 'Wedding DRESS فستان فرح',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676feeaba30fb.png',
            ),
            16 => 
            array (
                'id' => 24,
                'name' => 'LADIES U-WEAR ملابس داخلية نسائية',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc873c97.png',
            ),
            17 => 
            array (
                'id' => 25,
                'name' => 'LADIES TROUSER بنطلون نسائي',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc874b1d.png',
            ),
            18 => 
            array (
                'id' => 26,
                'name' => 'LADIES SHIRT قميص نسائي',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc875a19.png',
            ),
            19 => 
            array (
                'id' => 27,
                'name' => 'JACKET جاكيت',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc876519.png',
            ),
            20 => 
            array (
                'id' => 28,
                'name' => 'TOWEL-D فوطه كبيره',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc876f78.png',
            ),
            21 => 
            array (
                'id' => 29,
                'name' => 'TOWEL-S فوطه صغيره',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc87781a.png',
            ),
            22 => 
            array (
                'id' => 30,
                'name' => 'PARDA ستاره',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc878218.png',
            ),
            23 => 
            array (
                'id' => 31,
                'name' => 'BED SHEET-D شرشف كبير',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc878c0c.png',
            ),
            24 => 
            array (
                'id' => 32,
                'name' => 'BED SHEET-S شرشف صغير',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc879481.png',
            ),
            25 => 
            array (
                'id' => 33,
                'name' => 'SHAILA شيله',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc879d46.png',
            ),
            26 => 
            array (
                'id' => 34,
                'name' => 'UNEDR WEAR ملابس داخلية',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc87ac4b.png',
            ),
            27 => 
            array (
                'id' => 37,
                'name' => 'SHOES جوتي& نعال',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc87ceaf.png',
            ),
            28 => 
            array (
                'id' => 38,
                'name' => 'L.D-BAG',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc87d87f.png',
            ),
            29 => 
            array (
                'id' => 39,
                'name' => 'PILLOW مخده',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc87e2dc.png',
            ),
            30 => 
            array (
                'id' => 42,
                'name' => 'MEN TROUSER بنطلون رجالي',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc87fe2f.png',
            ),
            31 => 
            array (
                'id' => 46,
                'name' => 'SHAYLA شيله',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dceb36f306.png',
            ),
            32 => 
            array (
                'id' => 48,
                'name' => 'WZAR وزار',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc885501.png',
            ),
            33 => 
            array (
                'id' => 49,
                'name' => 'MUSAR OMAN مصر',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dffc8867cf.png',
            ),
            34 => 
            array (
                'id' => 51,
                'name' => 'T.SHIRT فانيله',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '675dceb3c27be.png',
            ),
            35 => 
            array (
                'id' => 52,
            'name' => 'عبائه رجاليه (بشت) Men bisht',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676ff54b4dc89.png',
            ),
            36 => 
            array (
                'id' => 53,
                'name' => 'قميص نوم نسائي  Women\'s nightgown',
                'price' => 0.0,
                'category_id' => 2,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676fef2fd16ff.png',
            ),
            37 => 
            array (
                'id' => 55,
                'name' => 'قفيض',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            38 => 
            array (
                'id' => 56,
                'name' => 'afrol افرول',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            39 => 
            array (
                'id' => 57,
                'name' => 'فوطه صغيره',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676ff50969cc0.png',
            ),
            40 => 
            array (
                'id' => 58,
                'name' => 'فوطه كبيره',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676ff50385b0b.png',
            ),
            41 => 
            array (
                'id' => 59,
                'name' => 'برنوص صغير',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            42 => 
            array (
                'id' => 60,
                'name' => 'برنوص كبير',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => NULL,
            ),
            43 => 
            array (
                'id' => 61,
                'name' => 'وجه طاوله',
                'price' => 0.0,
                'category_id' => 3,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676ff4d3c6697.png',
            ),
            44 => 
            array (
                'id' => 62,
            'name' => 'بيجامه نوم(دشاشه)',
                'price' => 0.0,
                'category_id' => 1,
                'description' => NULL,
                'image' => NULL,
                'available' => 1,
                'calories' => NULL,
                'prep_time' => NULL,
                'spice_level' => NULL,
                'is_vegan' => 0,
                'is_gluten_free' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'people_count' => '1',
                'image_url' => '676ff499e9acd.png',
            ),
        ));
        
        
    }
}